# Generated by Django 4.2.4 on 2023-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_company_members_companymember_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('founder', 'Founder'), ('employee', 'Employee')], default='employee', max_length=150),
        ),
    ]
